version: '3.9'
services:
  backend:
    container_name: blog-backend
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    env_file: backend/.env.prod
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    volumes:
      - postgres_data:/data/postgres
    image: postgres
    restart: always
    env_file:
       - backend/.env
  adminer:
    container_name: blogadminer
    image: adminer
    restart: always
    ports:
      - 8082:8080
  frontend:
    container_name: blog-frontend
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:80
    depends_on:
      - backend
volumes:
  postgres_data: